# Generated by Django 5.0.3 on 2025-01-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_actual_amount_group_estimated_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupexpense',
            old_name='added_by',
            new_name='created_by',
        ),
    ]
